### ISSUE TITLE
Logo Design For SMSGateway

### ISSUE THREAD

**Issue by zularizal** [samirk433/smsgateway#1]
Hi @samirk433 , I'm a graphic designer. I have reviewed your project and I like it.

But you don't have a logo yet, so I'm interested in contributing by creating a free logo for your project.

What do you think?

**Comment by samirk433** [comment]
> 
> 
> Hi @samirk433 , I'm a graphic designer. I have reviewed your project and I like it.
> 
> But you don't have a logo yet, so I'm interested in contributing by creating a free logo for your project.
> 
> What do you think?

This project was done for a company and is no longer maintained
